### ISSUE TITLE
SCADA TYPE ERROR

### ISSUE THREAD

**Issue by miguelob** [miguelob/ICS-Hacking#7]
hi @miguelob , thanks for the quick help, now it's working and I get into the menu.
Maybe I haven't understood the project correctly… I thought it's (also) meant to emulate ICS, e.g. a SCADA and S7 things, kind of like Snap7 or Bevywise do.
Trying to start the SCADA Lab I think I encountered a type error:
```
==========================

       ICS-Hacking

==========================
® by Miguel Oleo Blanco


1 -- S7Comm
2 -- S7Comm-plus
3 -- SCADA
4 -- Profinet & Profibus
5 -- Exit
Enter your choice: 3
Please, type in the destination IP: 192.168.1.10
Please, type in the RACK (DEFAULT IS 0): 0
Please, type in the the SLOT (DEFAULT IS 1): 1
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    plc.connect(IP,RACK,SLOT)   #Connects to the client
  File "/home/tobjasr/.local/lib/python3.8/site-packages/snap7/client.py", line 25, in f
    code = func(*args, **kw)
  File "/home/tobjasr/.local/lib/python3.8/site-packages/snap7/client.py", line 197, in connect
    c_int(rack), c_int(slot))
TypeError: an integer is required (got type str)
```

_Originally posted by @TobjasR in https://github.com/miguelob/ICS-Hacking/issues/6#issuecomment-1250343812_

**Comment by miguelob** [comment]
I'll be working on a solution this week and I'll post whenever it is fixed with the commit version and the new release.

**Comment by miguelob** [comment]
Hi @TobjasR a new commit was released. Try and check it out and see if it fix the issue. A new release package is not launched so you might get the new version from the [packet folder](https://github.com/miguelob/ICS-Hacking/tree/main/packet) in the repo.

**Comment by miguelob** [comment]
solved
